
version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "18:00"
      timezone: "Asia/Singapore"
    assignees:
      - "kenrick95"
    open-pull-requests-limit: 2
    groups:
      production-dependencies:
        dependency-type: "production"
      development-dependencies:
        dependency-type: "development"
