export default {
  attrs: {
    allow: {
      create: 'false',
      delete: 'false',
      update: 'false',
    },
  },
  trip: {
    bind: [
      'isTripPublic',
      'data.sharingLevel >= 2',
      'isTripEditor',
      "'editor' in data.ref('tripUser.role') && auth.id in data.ref('tripUser.user.$users.id')",
      'isTripOwner',
      "'owner' in data.ref('tripUser.role') && auth.id in data.ref('tripUser.user.$users.id')",
      'isTripViewer',
      "'viewer' in data.ref('tripUser.role') && auth.id in data.ref('tripUser.user.$users.id')",
    ],
    allow: {
      view: 'isTripPublic || isTripViewer || isTripEditor || isTripOwner',
      create: 'isTripOwner',
      delete: 'isTripOwner',
      update: 'isTripEditor || isTripOwner',
    },
  },
  user: {
    bind: ['isSelf', "auth.id in data.ref('$users.id')"],
    allow: {
      view: 'true',
      // Anyone can create a new user, e.g. from sharing to a new email
      create: 'true',
      delete: 'false',
      // Allow self to update any field; allow others only for link/unlink operations (no fields modified)
      update: "isSelf || 'tripUser' in request.modifiedFields",
    },
  },
  $users: {
    allow: {
      view: 'auth.id == data.id',
      create: 'true',
      delete: 'false',
      update: 'false',
    },
  },
  activity: {
    bind: [
      'isTripPublic',
      "2 in data.ref('trip.sharingLevel') || 3 in data.ref('trip.sharingLevel')",
      'isTripEditor',
      "'editor' in data.ref('trip.tripUser.role') && auth.id in data.ref('trip.tripUser.user.$users.id')",
      'isTripOwner',
      "'owner' in data.ref('trip.tripUser.role') && auth.id in data.ref('trip.tripUser.user.$users.id')",
      'isTripViewer',
      "'viewer' in data.ref('trip.tripUser.role') && auth.id in data.ref('trip.tripUser.user.$users.id')",
    ],
    allow: {
      view: 'isTripPublic || isTripViewer || isTripEditor || isTripOwner',
      create: 'isTripEditor || isTripOwner',
      delete: 'isTripEditor || isTripOwner',
      update: 'isTripEditor || isTripOwner',
    },
  },
  macroplan: {
    bind: [
      'isTripPublic',
      "2 in data.ref('trip.sharingLevel') || 3 in data.ref('trip.sharingLevel')",
      'isTripEditor',
      "'editor' in data.ref('trip.tripUser.role') && auth.id in data.ref('trip.tripUser.user.$users.id')",
      'isTripOwner',
      "'owner' in data.ref('trip.tripUser.role') && auth.id in data.ref('trip.tripUser.user.$users.id')",
      'isTripViewer',
      "'viewer' in data.ref('trip.tripUser.role') && auth.id in data.ref('trip.tripUser.user.$users.id')",
    ],
    allow: {
      view: 'isTripPublic || isTripViewer || isTripEditor || isTripOwner',
      create: 'isTripEditor || isTripOwner',
      delete: 'isTripEditor || isTripOwner',
      update: 'isTripEditor || isTripOwner',
    },
  },
  accommodation: {
    bind: [
      'isTripPublic',
      " 2 in data.ref('trip.sharingLevel')",
      'isTripEditor',
      "'editor' in data.ref('trip.tripUser.role') && auth.id in data.ref('trip.tripUser.user.$users.id')",
      'isTripOwner',
      "'owner' in data.ref('trip.tripUser.role') && auth.id in data.ref('trip.tripUser.user.$users.id')",
      'isTripViewer',
      "'viewer' in data.ref('trip.tripUser.role') && auth.id in data.ref('trip.tripUser.user.$users.id')",
    ],
    allow: {
      view: 'isTripPublic || isTripViewer || isTripEditor || isTripOwner',
      create: 'isTripEditor || isTripOwner',
      delete: 'isTripEditor || isTripOwner',
      update: 'isTripEditor || isTripOwner',
    },
  },
  expense: {
    bind: [
      'isTripPublic',
      "2 in data.ref('trip.sharingLevel') || 3 in data.ref('trip.sharingLevel')",
      'isTripEditor',
      "'editor' in data.ref('trip.tripUser.role') && auth.id in data.ref('trip.tripUser.user.$users.id')",
      'isTripOwner',
      "'owner' in data.ref('trip.tripUser.role') && auth.id in data.ref('trip.tripUser.user.$users.id')",
      'isTripViewer',
      "'viewer' in data.ref('trip.tripUser.role') && auth.id in data.ref('trip.tripUser.user.$users.id')",
      'isPublicShowExpenses',
      "!(false in data.ref('trip.publicShowExpenses'))",
      'isViewerShowExpenses',
      "!(false in data.ref('trip.viewerShowExpenses'))",
    ],
    allow: {
      view: 'isTripOwner || isTripEditor || (isTripViewer && isViewerShowExpenses) || (isTripPublic && isPublicShowExpenses)',
      create: 'isTripEditor || isTripOwner',
      delete: 'isTripEditor || isTripOwner',
      update: 'isTripEditor || isTripOwner',
    },
  },
  taskList: {
    bind: [
      'isTripPublic',
      "2 in data.ref('trip.sharingLevel') || 3 in data.ref('trip.sharingLevel')",
      'isTripEditor',
      "'editor' in data.ref('trip.tripUser.role') && auth.id in data.ref('trip.tripUser.user.$users.id')",
      'isTripOwner',
      "'owner' in data.ref('trip.tripUser.role') && auth.id in data.ref('trip.tripUser.user.$users.id')",
      'isTripViewer',
      "'viewer' in data.ref('trip.tripUser.role') && auth.id in data.ref('trip.tripUser.user.$users.id')",
      'isPublicShowTasks',
      "!(false in data.ref('trip.publicShowTasks'))",
      'isViewerShowTasks',
      "!(false in data.ref('trip.viewerShowTasks'))",
    ],
    allow: {
      view: 'isTripOwner || isTripEditor || (isTripViewer && isViewerShowTasks) || (isTripPublic && isPublicShowTasks)',
      create: 'isTripEditor || isTripOwner',
      delete: 'isTripEditor || isTripOwner',
      update: 'isTripEditor || isTripOwner',
    },
  },
  task: {
    bind: [
      'isTripPublic',
      "2 in data.ref('taskList.trip.sharingLevel') || 3 in data.ref('taskList.trip.sharingLevel')",
      'isTripEditor',
      "'editor' in data.ref('taskList.trip.tripUser.role') && auth.id in data.ref('taskList.trip.tripUser.user.$users.id')",
      'isTripOwner',
      "'owner' in data.ref('taskList.trip.tripUser.role') && auth.id in data.ref('taskList.trip.tripUser.user.$users.id')",
      'isTripViewer',
      "'viewer' in data.ref('taskList.trip.tripUser.role') && auth.id in data.ref('taskList.trip.tripUser.user.$users.id')",
      'isPublicShowTasks',
      "!(false in data.ref('taskList.trip.publicShowTasks'))",
      'isViewerShowTasks',
      "!(false in data.ref('taskList.trip.viewerShowTasks'))",
    ],
    allow: {
      view: 'isTripOwner || isTripEditor || (isTripViewer && isViewerShowTasks) || (isTripPublic && isPublicShowTasks)',
      create: 'isTripEditor || isTripOwner',
      delete: 'isTripEditor || isTripOwner',
      update: 'isTripEditor || isTripOwner',
    },
  },
  commentGroup: {
    bind: [
      'isTripPublic',
      "2 in data.ref('trip.sharingLevel') || 3 in data.ref('trip.sharingLevel')",
      'isTripEditor',
      "'editor' in data.ref('trip.tripUser.role') && auth.id in data.ref('trip.tripUser.user.$users.id')",
      'isTripOwner',
      "'owner' in data.ref('trip.tripUser.role') && auth.id in data.ref('trip.tripUser.user.$users.id')",
      'isTripViewer',
      "'viewer' in data.ref('trip.tripUser.role') && auth.id in data.ref('trip.tripUser.user.$users.id')",
      'isPublicShowComments',
      "!(false in data.ref('trip.publicShowComments'))",
      'isViewerShowComments',
      "!(false in data.ref('trip.viewerShowComments'))",
    ],
    allow: {
      view: 'isTripOwner || isTripEditor || (isTripViewer && isViewerShowComments) || (isTripPublic && isPublicShowComments)',
      create: 'isTripEditor || isTripOwner',
      delete: 'isTripEditor || isTripOwner',
      update: 'isTripEditor || isTripOwner',
    },
  },
  comment: {
    bind: [
      'isTripPublic',
      "2 in data.ref('group.trip.sharingLevel') || 3 in data.ref('group.trip.sharingLevel')",
      'isTripEditor',
      "'editor' in data.ref('group.trip.tripUser.role') && auth.id in data.ref('group.trip.tripUser.user.$users.id')",
      'isTripOwner',
      "'owner' in data.ref('group.trip.tripUser.role') && auth.id in data.ref('group.trip.tripUser.user.$users.id')",
      'isTripViewer',
      "'viewer' in data.ref('group.trip.tripUser.role') && auth.id in data.ref('group.trip.tripUser.user.$users.id')",
      'isPublicShowComments',
      "!(false in data.ref('group.trip.publicShowComments'))",
      'isViewerShowComments',
      "!(false in data.ref('group.trip.viewerShowComments'))",
    ],
    allow: {
      view: 'isTripOwner || isTripEditor || (isTripViewer && isViewerShowComments) || (isTripPublic && isPublicShowComments)',
      create: 'isTripEditor || isTripOwner',
      delete: 'isTripEditor || isTripOwner',
      update: 'isTripEditor || isTripOwner',
    },
  },
  tripUser: {
    bind: [
      'isTripPublic',
      "2 in data.ref('trip.sharingLevel') || 3 in data.ref('trip.sharingLevel')",
      'isTripEditor',
      "'editor' in data.ref('trip.tripUser.role') && auth.id in data.ref('trip.tripUser.user.$users.id')",
      'isTripOwner',
      "'owner' in data.ref('trip.tripUser.role') && auth.id in data.ref('trip.tripUser.user.$users.id')",
      'isTripViewer',
      "'viewer' in data.ref('trip.tripUser.role') && auth.id in data.ref('trip.tripUser.user.$users.id')",
    ],
    allow: {
      view: 'isTripPublic || isTripViewer || isTripEditor || isTripOwner',
      create: 'isTripOwner',
      delete: 'isTripOwner',
      update: 'isTripOwner',
    },
  },
};
