name: Deploy

on:
  push:
    branches: ['main']

jobs:
  deploy:
    concurrency:
      group: ci-${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4.0.0
        with:
          version: 9.7.0
      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install
      - name: Lint
        run: pnpm lint
      - name: Build
        run: pnpm build
      - uses: up9cloud/action-rsync@v1.4
        env:
          HOST: ${{env.DEPLOY_HOST}}
          KEY: ${{secrets.DEPLOY_SSH_KEY}}
          TARGET: ${{env.DEPLOY_TARGET}}
          SOURCE: './dist/'
          MODE: push
          VERBOSE: true
          PORT: ${{env.DEPLOY_PORT}}
          USER: ${{env.DEPLOY_USER}}
          ARGS: -avz --exclude-from=.gitignore --exclude=/.git/ --exclude=/.github/
