name: Testing

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  test:
    concurrency:
      group: ci-${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    runs-on: ubuntu-24.04
    outputs:
      build-artifact-id: ${{ steps.artifact-upload-step.outputs.artifact-id }}
    env:
      INSTANT_APP_ID: ${{ vars.INSTANT_APP_ID }}
      MAPTILER_API_KEY: ${{ vars.MAPTILER_API_KEY }}
      MAPTILER_MAP_STYLE_LIGHT: ${{ vars.MAPTILER_MAP_STYLE_LIGHT }}
      MAPTILER_MAP_STYLE_DARK: ${{ vars.MAPTILER_MAP_STYLE_DARK }}
      SENTRY_DSN: ${{ vars.SENTRY_DSN }}
      SENTRY_ENABLED: ${{ vars.SENTRY_ENABLED }}
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4.0.0
      - name: Use Node.js 22
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install
      - name: Biome CI
        run: pnpm biome:ci
      - name: Typecheck
        run: pnpm typecheck
      - name: Test
        run: pnpm test
      - name: Build
        run: pnpm build
      - uses: actions/upload-artifact@v4
        id: artifact-upload-step
        with:
          name: build-artifact
          path: dist/
          if-no-files-found: error
